name: Copy REMARK metadata
on:
  push:
    branches:
      - master
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml==0.6.0
      - name: copy metadata
        run: python scripts/populate_materials.py
      - name: update gh-pages branch
        run: |
          git checkout -b gh-pages
          git add .
          git commit -m "autopull REMARKs $(date)"
